version: "3.3"

services:
  api:
    image: ${REGISTRY}quiz-api:${TAG}
    build:
      context: .
      dockerfile: ./src/Quiz.Api/Dockerfile
      args:
        api: ${QUIZ_API}
        domain: ${QUIZ_DOMAIN}
        unitTests: ${QUIZ_UNITTESTS}
  
  ui:
    image: ${REGISTRY}quiz-ui:${TAG}
    build:
      context: .
      dockerfile: ./src/quiz-ui/Dockerfile

  cli:
    image: ${REGISTRY}quiz-cli:${TAG}
    build:
      context: .
      dockerfile: ./src/quiz-cli/Dockerfile

  ci:
    image: ${REGISTRY}jenkins:${TAG}
    build:
      context: ./jenkins 
      dockerfile: Dockerfile