version: "3.3"

services:
  gateway:
    ports:
      - "80:80"

  commands:
    ports:
      - "81:80"
    environment: 
      dbconnection: ${DB_CONNECTION}
      messagebroker: ${MESSAGE_BROKER}
  
  queries:
    ports:
      - "82:80"
    environment: 
      messagebroker: ${MESSAGE_BROKER}

  ui:
    ports:
      - "8080:80"