version: '3.3'

services:
  messagebroker:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: changeit

  