version: "3.1"

services:
  api:
    image: ${REGISTRY}quiz-api:${TAG}
    ports:
      - "81:80"
    environment: 
      - EVENT_STORE=tcp://admin:changeit@eventstore:1113
      - EVENT_STORE_MANAGER_HOST=eventstore:2113
  
  results:
    image: ${REGISTRY}quiz-results:${TAG}
    ports:
      - "82:80"
    environment: 
      - EVENT_STORE=tcp://admin:changeit@eventstore:1113
      - EVENT_STORE_MANAGER_HOST=eventstore:2113

  ui:
    image: ${REGISTRY}quiz-ui:${TAG}
    build:
      context: ${BUILD_CONTEXT}
      dockerfile: ./src/quiz-ui/Dockerfile
    depends_on:
      - api
      - results
    ports:
      - "80:5000"

  eventstore:
    image: eventstore/eventstore
    ports:
      - "2113:2113"