version: "3.1"

services:
  api:
    image: ${REGISTRY}quiz-api:${TAG}
    build:
      context: ${BUILD_CONTEXT}
      dockerfile: ./src/Quiz.Api/Dockerfile
    ports:
      - "81:80"
    environment: 
      - EVENT_STORE=tcp://admin:changeit@eventstore:1113
      - EVENT_STORE_MANAGER_HOST=eventstore:2113
      - STREAM_NAME=QuestionAnswers
      - BUS_CONNECTION=host=bus;username=guest;password=guest
  
  results:
    image: ${REGISTRY}quiz-results:${TAG}
    build:
      context: ${BUILD_CONTEXT}
      dockerfile: ./src/Quiz.Results/Dockerfile
    ports:
      - "82:80"
    environment: 
      - EVENT_STORE=tcp://admin:changeit@eventstore:1113
      - EVENT_STORE_MANAGER_HOST=eventstore:2113
      - STREAM_NAME=QuestionAnswers

  ui:
    image: ${REGISTRY}quiz-ui:${TAG}
    build:
      context: ${BUILD_CONTEXT}
      dockerfile: ./src/quiz-ui/Dockerfile
    depends_on:
      - api
      - results
    ports:
      - "80:5000"

  eventstore:
    image: eventstore/eventstore
    ports:
      - "2113:2113"

  bus:
    image: rabbitmq:3-management
    ports:
      - "8081:15672" 
