version: "3.1"

services:
  api:
    image: paulopez/aspnetcore-debug
    volumes: 
      - ./src/Quiz.Api/bin/PublishOutput/:/app
      - ~/.nuget/packages:/root/.nuget/packages:ro
  
  results:
    image: paulopez/aspnetcore-debug
    volumes: 
      - ./src/Quiz.Results/bin/PublishOutput/:/app
      - ~/.nuget/packages:/root/.nuget/packages:ro
