imageRegistry: localhost:30400
imageTag: latest
ingressHost: quiz.internal

services:
  - name: ui
    image: quiz-ui
    ingress:
      annotations: {}

  - name: commands
    image: quiz-commands
    env:
      - messagebroker
      - dbconnection
    ingress:
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
      path: /commands

  - name: queries
    image: quiz-queries
    env:
      - messagebroker
      - dbconnection
    ingress:
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
      path: /queries 
   
integration:
  enabled: true
  tests:
  - name: integration-tests
    image: quiz-integration-tests
    env:
      - messagebroker
      - dbconnection
    command: "sleep 20;dotnet test --no-build"

end2end:
  enabled: true
  name: end2end-tests
  image: quiz-end2end-tests

rabbitmq:
  ingress:
    enabled: true
  rabbitmq:
    username: guest
    password: changeit

postgresql:
  postgresUser: postgres
  postgresPassword: changeit
