version: "3"

services:
  vote:
    image: quiz-voting
    ports:
      - "5000:80"
    networks:
      - front-tier
      - back-tier
    depends_on: 
      - eventstore
    environment: 
      - EVENT_STORE=tcp://admin:changeit@eventstore:1113
    # deploy:
    #   placement:
    #     constraints: [node.role == worker]

  eventstore:
    image: eventstore/eventstore
    container_name: eventstore-node
    ports:
      - "2113:2113"
      - "1113:1113"
    networks:
      - back-tier
    deploy:
      placement:
        constraints: [node.role == manager]

  result:
    image: quiz-results
    networks:
      - back-tier
    environment: 
      - EVENT_STORE=tcp://admin:changeit@eventstore:1113
      - STREAM_NAME=QuestionAnswers
    depends_on: 
      - eventstore

networks:
  front-tier:
  back-tier: