version: "3"

services:
  vote:
    image: quiz-voting:${SHA_COMMIT}
    ports:
      - "5000:80"
    networks:
      - front-tier
      - back-tier
    depends_on: 
      - setup
      - eventstore
    environment: 
      - EVENT_STORE=tcp://admin:changeit@eventstore:1113

  eventstore:
    image: eventstore/eventstore
    ports:
      - "2113:2113"
      - "1113:1113"
    networks:
      - back-tier
    deploy:
      placement:
        constraints: [node.role == manager]

  setup:
    image: quiz-setup:${SHA_COMMIT}
    networks:
      - back-tier
    environment: 
      - EVENT_STORE=tcp://admin:changeit@eventstore:1113
      - EVENT_STORE_MANAGER_HOST=eventstore:2113
    depends_on: 
      - eventstore

  result:
    image: quiz-results:${SHA_COMMIT}
    networks:
      - back-tier
    environment: 
      - EVENT_STORE=tcp://admin:changeit@eventstore:1113
    depends_on: 
      - setup
      - eventstore
  
  ci:
    image: awesome-ci:${SHA_COMMIT}
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - front-tier
    environment: 
      - CI_TOKEN=${CI_TOKEN}

networks:
  front-tier:
  back-tier: