version: "3"

services:
  registry: 
    image: registry:2
    ports:
      - "5000:5000"

  viz:
    image: manomarks/visualizer
    ports:
      - "9090:8080"
    environment: 
      - PORT=9090
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints: [node.role == manager]

  eventstore:
    image: eventstore/eventstore
    ports:
      - "2113:2113"
      - "1113:1113"
    networks:
      - back-tier
    logging:
      driver: "json-file"
    deploy:
      placement:
        constraints: [node.role == manager]
        
networks:
  back-tier: