version: "3"

services:
  vote:
    image: ${REGISTRY}quiz-voting:${SHA_COMMIT}
    ports:
      - "81:80"
    networks:
      - front-tier
      - back-tier
    depends_on: 
      - setup
      - eventstore
    environment: 
      - EVENT_STORE=tcp://admin:changeit@eventstore:1113

  eventstore:
    image: eventstore/eventstore
    ports:
      - "2113:2113"
      - "1113:1113"
    networks:
      - back-tier
    deploy:
      placement:
        constraints: [node.role == manager]

  setup:
    image: ${REGISTRY}quiz-setup:${SHA_COMMIT}
    networks:
      - back-tier
    environment: 
      - EVENT_STORE=tcp://admin:changeit@eventstore:1113
      - EVENT_STORE_MANAGER_HOST=eventstore:2113
    depends_on: 
      - eventstore

  result:
    image: ${REGISTRY}quiz-results:${SHA_COMMIT}
    networks:
      - back-tier
    environment: 
      - EVENT_STORE=tcp://admin:changeit@eventstore:1113
    depends_on: 
      - setup
      - eventstore
  
  ci:
    image: ${REGISTRY}awesome-ci:${SHA_COMMIT}
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - front-tier
    environment: 
      - CI_TOKEN=${CI_TOKEN}
      - REGISTRY=${REGISTRY}
    deploy:
      mode: replicated
      replicas: 2
      # service restart policy
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      # service update configuration
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: continue
        monitor: 60s
        max_failure_ratio: 0.3

networks:
  front-tier:
  back-tier: