version: "3"

services:
  setup:
    image: ${REGISTRY}quiz-setup:${SHA_COMMIT}
    networks:
      - back-tier
    environment: 
      - EVENT_STORE_MANAGER_HOST=eventstore:2113
    depends_on: 
      - eventstore
    logging:
      driver: "json-file"
    deploy:
      placement:
        constraints: [node.role == worker]
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2
        window: 120s   

networks:
  back-tier: