apiVersion: v1
kind: Service
metadata:
  name: quiz-api
spec:
  type: LoadBalancer 
  ports: 
  - port: 80
  selector:
    app: quiz-api
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: quiz-api
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: quiz-api
    spec:
      containers:
      - name: quiz-api
        image: paulopez/quiz-api:latest
        ports:
        - containerPort: 80
        env:
        - name: dbconnection
          value: "Username=admin;Password=changeit;Host=db;Port=5432"
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: db 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: postgres
        ports:
        - containerPort: 5432
          name: db
        env:
        - name: POSTGRES_USER
          value: admin
        - name: POSTGRES_PASSWORD
          value: changeit
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  ports:
  - port: 5432
  selector:
    app: db