---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: quiz
#  annotations:
#   nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: quiz.io
    http:
      paths:
      - path: /
        backend:
          serviceName: quiz-ui
          servicePort: 80
      - path: /api
        backend:
          serviceName: quiz-api
          servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: quiz-api
spec:
  ports: 
  - port: 80
  selector:
    app: quiz-api
---
apiVersion: v1
kind: Service
metadata:
  name: quiz-ui
spec:
  ports: 
  - port: 80
  selector:
    app: quiz-ui
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: quiz-ui
spec:
  template:
    metadata:
      labels:
        app: quiz-ui
    spec:
      containers:
      - name: quiz-ui
        imagePullPolicy: Always
        image: ${REGISTRY}/quiz-ui:${TAG}
        ports:
        - containerPort: 80
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: quiz-api
spec:
  template:
    metadata:
      labels:
        app: quiz-api
    spec:
      containers:
      - name: quiz-api
        imagePullPolicy: Always
        image: ${REGISTRY}/quiz-api:${TAG}
        ports:
        - containerPort: 80
        env:
        - name: dbconnection
          value: "Username=admin;Password=changeit;Host=db;Port=5432"
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: db 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: postgres
        ports:
        - containerPort: 5432
          name: db
        env:
        - name: POSTGRES_USER
          value: admin
        - name: POSTGRES_PASSWORD
          value: changeit
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  ports:
  - port: 5432
  selector:
    app: db