version: "3"

services:
  vote:
    image: quiz-voting
    ports:
      - "81:81"
    environment: 
      - EVENT_STORE=tcp://admin:changeit@eventstore:1113
      - EVENT_STORE_MANAGER_HOST=eventstore:2113
      - ASPNETCORE_URLS=https://*:81
  
  results:
    image: quiz-results
    ports:
      - "82:82"
    environment: 
      - EVENT_STORE=tcp://admin:changeit@eventstore:1113
      - ASPNETCORE_URLS=https://*:82

  ui:
    image: quiz-ui
    depends_on:
      - vote
      - results
    ports:
      - "80:5000"

  setup:
    image: quiz-setup
    depends_on:
      - eventstore
    environment: 
      - EVENT_STORE=tcp://admin:changeit@eventstore:1113
      - EVENT_STORE_MANAGER_HOST=eventstore:2113

  eventstore:
    image: eventstore/eventstore
    ports:
      - "2113:2113"
      - "1113:1113"
