version: "3"

services:
  api:
    image: quiz-api
    ports:
      - "81:80"
    environment: 
      - EVENT_STORE=tcp://admin:changeit@eventstore:1113
      - EVENT_STORE_MANAGER_HOST=eventstore:2113
      - STREAM_NAME=QuestionAnswers
  
  results:
    image: quiz-results
    ports:
      - "82:80"
    environment: 
      - EVENT_STORE=tcp://admin:changeit@eventstore:1113
      - EVENT_STORE_MANAGER_HOST=eventstore:2113
      - STREAM_NAME=QuestionAnswers

  ui:
    image: quiz-ui
    depends_on:
      - api
      - results
    ports:
      - "80:5000"

  eventstore:
    image: eventstore/eventstore
    ports:
      - "2113:2113"
      - "1113:1113"
