version: "3"

services:
  vote:
    image: quiz-voting
    ports:
      - "81:80"
    environment: 
      - EVENT_STORE=tcp://admin:changeit@eventstore:1113
  
  result:
    image: quiz-results
    ports:
      - "82:80"
    environment: 
      - EVENT_STORE=tcp://admin:changeit@eventstore:1113

  setup:
    image: quiz-setup
    environment: 
      - EVENT_STORE=tcp://admin:changeit@eventstore:1113
      - EVENT_STORE_MANAGER_HOST=eventstore:2113