{{- $fullName := include "quiz.fullname" . -}}
{{- $name := include "quiz.name" . -}}
{{- $chart := include "quiz.chart" . -}}
{{- $releaseName := .Release.Name -}}
{{- $releaseService := .Release.Service -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ $name }}
    chart: {{ $chart }}
    release: {{ $releaseName }}
    heritage: {{ $releaseService }}
data:
  messagebroker: {{ printf "host=%s-rabbitmq;username=%s;password=%s" $name .Values.rabbitmq.rabbitmq.user .Values.rabbitmq.rabbitmq.password | b64enc | quote }}
  dbconnection: {{ printf "Host=%s-postgresql;Username=%s;Password=%s" $name .Values.postgresql.postgresUser .Values.postgresql.postgresPassword | b64enc | quote }}