apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: jenkins-ci
spec:
 replicas: 1
 template:
  metadata:
   labels:
    name: jenkins-ci
  spec:
   containers:
   - name: jenkins-ci
     imagePullPolicy: Always
     image: paulopez/jenkins:latest
     ports:
     - containerPort: 8080
     - containerPort: 50000
     readinessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 40
      periodSeconds: 20
     securityContext: 
       privileged: true 
     env:
      - name: REGISTRY
        value: paulopez
      - name: DOCKER_USER
        value: paulopez
      - name: DOCKER_PASSWORD
        valueFrom:
          secretKeyRef:
            name: docker-credentials 
            key: docker-pass
     volumeMounts: 
       - mountPath: /var/run
         name: docker-sock 
       - mountPath: /var/jenkins_home
         name: jenkins-home 
       - mountPath: /run/secrets
         name: credentials
         readOnly: true
   volumes: 
     - name: docker-sock
       hostPath: 
         path: /var/run
     - name: jenkins-home
       hostPath: 
         path: /var/jenkins_home
     - name: credentials
       secret:
        secretName: jenkins-user-pass
        items:
         - key: jenkins-user
           path: jenkins-user
         - key: jenkins-pass
           path: jenkins-pass
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-ci
spec:
 type: NodePort
 ports:
   - name: jenkins
     port: 8080
     targetPort: 8080
   - name: jenkins-agent
     port: 50000
     targetPort: 50000
 selector:
   name: jenkins-ci
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: jenkins-ci
#  annotations:
#   nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  backend:
    serviceName: default-http-backend
    servicePort: 80
  rules:
  - host: quiz-ci.io
    http:
      paths:
      - path: /
        backend:
          serviceName: jenkins-ci 
          servicePort: 8080