apiVersion: v1
kind: Secret
metadata:
  name: {{ template "quiz-ci.name" . }}-credentials
  labels:
    app: {{ template "quiz-ci.name" . }}
    chart: {{ template "quiz-ci.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  credentials.xml: {{ include "credentials.xml.tpl" . | trim | b64enc | quote}}
